# Generated by Django 2.1.3 on 2018-11-27 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField(default=0)),
                ('date_contest', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_ten', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TenContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ten_contests', to='perfil.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='TenTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_tip', models.DateField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipies', to='perfil.Lottery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tentips',
            name='tips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipies', to='perfil.Tips'),
        ),
        migrations.AddField(
            model_name='contest',
            name='lottery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='perfil.Lottery'),
        ),
    ]
